### ISSUE TITLE
Can't build - keyset doesn't exist

### ISSUE THREAD

**Issue by deostroll** [remobjects/internetpack#2]
I am trying to build `RemObjects.InternetPack.2015.sln` and I get a build error as follows:

```
1>------ Build started: Project: RemObjects.InternetPack.2015, Configuration: Debug Any CPU ------
1>CSC : error CS7028: Error signing output with public key from container 'RemObjectsSoftware' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
2>------ Build started: Project: RemObjects.InternetPack.VirtualFTP.2015, Configuration: Debug Any CPU ------
2>CSC : error CS0006: Metadata file 'D:\VSProjects\internet-pack\bin\RemObjects.InternetPack.dll' could not be found
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by carlokok** [comment]
you have to create a local keyset with that name to build Internet pack.

**Comment by deostroll** [comment]
Sorry. Not that much into crypto...can you link to some articles showing how to exactly do that...

**Comment by carlokok** [comment]
Start "Visual Studio 2013/2015 Command Prompt" 
run: sn -k MyKey   
(this generates a MyKey file, save it somewhere)
run: sn -i MyKey RemObjectsSoftware
(this installs the key in the store)
that should be it.
